// <auto-generated />
using System;
using EmployeeLeaveApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EmployeeLeaveApi.Migrations
{
    [DbContext(typeof(LeaveDbContext))]
    [Migration("20260531025247_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EmployeeLeaveApi.Models.LeaveBalance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AllocatedDays")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<int>("LeaveTypeId")
                        .HasColumnType("int");

                    b.Property<decimal>("PendingDays")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("UsedDays")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("LeaveTypeId");

                    b.ToTable("LeaveBalances");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AllocatedDays = 10m,
                            EmployeeId = 2,
                            LeaveTypeId = 1,
                            PendingDays = 0m,
                            UsedDays = 0m
                        },
                        new
                        {
                            Id = 2,
                            AllocatedDays = 12m,
                            EmployeeId = 2,
                            LeaveTypeId = 2,
                            PendingDays = 0m,
                            UsedDays = 0m
                        },
                        new
                        {
                            Id = 3,
                            AllocatedDays = 20m,
                            EmployeeId = 2,
                            LeaveTypeId = 3,
                            PendingDays = 0m,
                            UsedDays = 0m
                        },
                        new
                        {
                            Id = 4,
                            AllocatedDays = 10m,
                            EmployeeId = 3,
                            LeaveTypeId = 1,
                            PendingDays = 0m,
                            UsedDays = 0m
                        },
                        new
                        {
                            Id = 5,
                            AllocatedDays = 12m,
                            EmployeeId = 3,
                            LeaveTypeId = 2,
                            PendingDays = 0m,
                            UsedDays = 0m
                        },
                        new
                        {
                            Id = 6,
                            AllocatedDays = 20m,
                            EmployeeId = 3,
                            LeaveTypeId = 3,
                            PendingDays = 0m,
                            UsedDays = 0m
                        },
                        new
                        {
                            Id = 7,
                            AllocatedDays = 10m,
                            EmployeeId = 4,
                            LeaveTypeId = 1,
                            PendingDays = 0m,
                            UsedDays = 0m
                        },
                        new
                        {
                            Id = 8,
                            AllocatedDays = 12m,
                            EmployeeId = 4,
                            LeaveTypeId = 2,
                            PendingDays = 0m,
                            UsedDays = 0m
                        },
                        new
                        {
                            Id = 9,
                            AllocatedDays = 20m,
                            EmployeeId = 4,
                            LeaveTypeId = 3,
                            PendingDays = 0m,
                            UsedDays = 0m
                        });
                });

            modelBuilder.Entity("EmployeeLeaveApi.Models.LeaveRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ActionedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("AppliedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ApprovedByManagerId")
                        .HasColumnType("int");

                    b.Property<string>("AttachmentFileName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AttachmentPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("LeaveTypeId")
                        .HasColumnType("int");

                    b.Property<string>("ManagerRemarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TotalDays")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ApprovedByManagerId");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("LeaveTypeId");

                    b.ToTable("LeaveRequests");
                });

            modelBuilder.Entity("EmployeeLeaveApi.Models.LeaveType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("DefaultDays")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("RequiresAttachment")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("LeaveTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DefaultDays = 10m,
                            Name = "Sick Leave",
                            RequiresAttachment = true
                        },
                        new
                        {
                            Id = 2,
                            DefaultDays = 12m,
                            Name = "Casual Leave",
                            RequiresAttachment = false
                        },
                        new
                        {
                            Id = 3,
                            DefaultDays = 20m,
                            Name = "Annual Leave",
                            RequiresAttachment = false
                        },
                        new
                        {
                            Id = 4,
                            DefaultDays = 90m,
                            Name = "Maternity Leave",
                            RequiresAttachment = true
                        },
                        new
                        {
                            Id = 5,
                            DefaultDays = 15m,
                            Name = "Paternity Leave",
                            RequiresAttachment = true
                        });
                });

            modelBuilder.Entity("EmployeeLeaveApi.Models.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("EmployeeLeaveApi.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("JoinDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ManagerId")
                        .HasColumnType("int");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProfilePictureUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("ManagerId");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Department = "HR & IT",
                            Email = "admin@company.com",
                            FirstName = "System",
                            JoinDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            LastName = "Administrator",
                            PasswordHash = "PrP+ZrMeO00Q+nC1ytSccRIpSvauTkdqHEBRVdRaoSE=",
                            Role = "Admin",
                            Username = "admin"
                        },
                        new
                        {
                            Id = 2,
                            Department = "Engineering",
                            Email = "bob@company.com",
                            FirstName = "Bob",
                            JoinDate = new DateTime(2025, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            LastName = "Manager",
                            PasswordHash = "ST/ct5DjWan4v64mDLjfEqsMJIU+E9TZtiOcM9e3JYo=",
                            Role = "Manager",
                            Username = "bob"
                        },
                        new
                        {
                            Id = 3,
                            Department = "Engineering",
                            Email = "alice@company.com",
                            FirstName = "Alice",
                            JoinDate = new DateTime(2025, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            LastName = "Smith",
                            ManagerId = 2,
                            PasswordHash = "g89+N06D2i7m7NylitWyi6OPzlaL+dKhuceunMH+nnw=",
                            Role = "Employee",
                            Username = "alice"
                        },
                        new
                        {
                            Id = 4,
                            Department = "Engineering",
                            Email = "charlie@company.com",
                            FirstName = "Charlie",
                            JoinDate = new DateTime(2025, 4, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            LastName = "Brown",
                            ManagerId = 2,
                            PasswordHash = "1V382PF6ecIMos83+nLQ/mhzsbWAb+f0m0QZmmoTWno=",
                            Role = "Employee",
                            Username = "charlie"
                        });
                });

            modelBuilder.Entity("EmployeeLeaveApi.Models.LeaveBalance", b =>
                {
                    b.HasOne("EmployeeLeaveApi.Models.User", "Employee")
                        .WithMany("LeaveBalances")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EmployeeLeaveApi.Models.LeaveType", "LeaveType")
                        .WithMany()
                        .HasForeignKey("LeaveTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("LeaveType");
                });

            modelBuilder.Entity("EmployeeLeaveApi.Models.LeaveRequest", b =>
                {
                    b.HasOne("EmployeeLeaveApi.Models.User", "ApprovedByManager")
                        .WithMany()
                        .HasForeignKey("ApprovedByManagerId");

                    b.HasOne("EmployeeLeaveApi.Models.User", "Employee")
                        .WithMany("LeaveRequests")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EmployeeLeaveApi.Models.LeaveType", "LeaveType")
                        .WithMany()
                        .HasForeignKey("LeaveTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ApprovedByManager");

                    b.Navigation("Employee");

                    b.Navigation("LeaveType");
                });

            modelBuilder.Entity("EmployeeLeaveApi.Models.Notification", b =>
                {
                    b.HasOne("EmployeeLeaveApi.Models.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("EmployeeLeaveApi.Models.User", b =>
                {
                    b.HasOne("EmployeeLeaveApi.Models.User", "Manager")
                        .WithMany("DirectReports")
                        .HasForeignKey("ManagerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Manager");
                });

            modelBuilder.Entity("EmployeeLeaveApi.Models.User", b =>
                {
                    b.Navigation("DirectReports");

                    b.Navigation("LeaveBalances");

                    b.Navigation("LeaveRequests");

                    b.Navigation("Notifications");
                });
#pragma warning restore 612, 618
        }
    }
}
